### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/Floppy#4]

**Comment by ArtPoon** [comment]
@galmog @Abayomi-Olabode please weigh in on preferred license ASAP

**Comment by Abayomi-Olabode** [comment]
@ArtPoon I suggest we leave it open, in the public domain with free access to modify.

**Comment by ArtPoon** [comment]
Of course, but which license?  MIT?  GPL?

**Comment by Abayomi-Olabode** [comment]
@ArtPoon oh Sorry. I would say MIT.

**Comment by galmog** [comment]
MIT sounds good
